# exemplo deu um netlify.toml
[build]
  command = "npm start"
  functions = "netlify/functions"
  publish = "dist"

# Redirecionamento de todas as rotas para /index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200